#!/usr/bin/env python3
"""Build a single-file FluidBalls HTML document.

Usage:
    python build_single.py
    python build_single.py --output fluidballs-webgl-single.html

The script inlines local stylesheets and classic JavaScript files referenced by
index.html. It intentionally rejects paths outside the project directory.
"""

from __future__ import annotations

import argparse
import html
import re
from pathlib import Path


STYLESHEET_RE = re.compile(
    r"(?P<indent>^[ \t]*)<link\b(?P<attrs>[^>]*?)>",
    re.IGNORECASE | re.MULTILINE,
)

SCRIPT_RE = re.compile(
    r"(?P<indent>^[ \t]*)<script\b(?P<attrs>[^>]*?\bsrc\s*=\s*(?P<quote>['\"])(?P<src>.*?)(?P=quote)[^>]*)>\s*</script>",
    re.IGNORECASE | re.MULTILINE,
)

ATTRIBUTE_RE = re.compile(
    r"(?P<name>[\w:-]+)(?:\s*=\s*(?P<quote>['\"])(?P<value>.*?)(?P=quote))?",
    re.DOTALL,
)


def parse_attributes(raw_attributes: str) -> dict[str, str]:
    """Parse the small subset of HTML attributes needed by this bundler."""
    attributes: dict[str, str] = {}

    for match in ATTRIBUTE_RE.finditer(raw_attributes):
        name = match.group("name").lower()
        value = html.unescape(match.group("value") or "")
        attributes[name] = value

    return attributes


def resolve_local_file(project_root: Path, reference: str) -> Path:
    """Resolve a local reference and ensure it stays inside project_root."""
    if not reference:
        raise ValueError("Encountered an empty local resource reference.")

    if reference.startswith(("http://", "https://", "//", "data:", "blob:")):
        raise ValueError(f"Refusing to inline non-local resource: {reference}")

    candidate = (project_root / reference).resolve()
    root = project_root.resolve()

    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"Refusing to read outside the project directory: {reference}") from exc

    if not candidate.is_file():
        raise FileNotFoundError(f"Referenced resource does not exist: {candidate}")

    return candidate


def indent_content(content: str, indent: str) -> str:
    """Indent embedded content while preserving blank lines."""
    return "\n".join(f"{indent}{line}" if line else "" for line in content.splitlines())


def inline_stylesheets(document: str, project_root: Path) -> tuple[str, list[Path]]:
    inlined: list[Path] = []

    def replace(match: re.Match[str]) -> str:
        attributes = parse_attributes(match.group("attrs"))
        rel_tokens = {token.lower() for token in attributes.get("rel", "").split()}
        href = attributes.get("href")

        if "stylesheet" not in rel_tokens or not href:
            return match.group(0)

        stylesheet = resolve_local_file(project_root, href)
        css = stylesheet.read_text(encoding="utf-8")
        # A literal closing style tag would terminate the element during HTML parsing.
        css = re.sub(r"</style", r"<\\/style", css, flags=re.IGNORECASE)
        indent = match.group("indent")
        body_indent = f"{indent}  "
        inlined.append(stylesheet)

        return (
            f'{indent}<style data-inlined-from="{html.escape(href, quote=True)}">\n'
            f"{indent_content(css, body_indent)}\n"
            f"{indent}</style>"
        )

    return STYLESHEET_RE.sub(replace, document), inlined


def inline_scripts(document: str, project_root: Path) -> tuple[str, list[Path]]:
    inlined: list[Path] = []

    def replace(match: re.Match[str]) -> str:
        attributes = parse_attributes(match.group("attrs"))
        source = match.group("src")
        script_type = attributes.get("type", "").strip().lower()

        if script_type == "module":
            raise ValueError(
                f"Module script {source!r} cannot be safely flattened by this simple bundler."
            )

        script = resolve_local_file(project_root, source)
        javascript = script.read_text(encoding="utf-8")
        # The HTML parser recognizes this token even when it appears inside a JS string.
        javascript = re.sub(r"</script", r"<\\/script", javascript, flags=re.IGNORECASE)
        indent = match.group("indent")
        body_indent = f"{indent}  "
        inlined.append(script)

        return (
            f'{indent}<script data-inlined-from="{html.escape(source, quote=True)}">\n'
            f"{indent_content(javascript, body_indent)}\n"
            f"{indent}</script>"
        )

    return SCRIPT_RE.sub(replace, document), inlined


def build(source: Path, output: Path) -> tuple[list[Path], list[Path]]:
    project_root = source.parent.resolve()
    document = source.read_text(encoding="utf-8")

    document, stylesheets = inline_stylesheets(document, project_root)
    document, scripts = inline_scripts(document, project_root)

    banner = (
        "<!-- Generated by build_single.py. "
        "Edit the source files, then rebuild this file. -->\n"
    )

    if document.startswith("<!doctype") or document.startswith("<!DOCTYPE"):
        first_newline = document.find("\n")
        document = document[: first_newline + 1] + banner + document[first_newline + 1 :]
    else:
        document = banner + document

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(document, encoding="utf-8", newline="\n")
    return stylesheets, scripts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=Path(__file__).with_name("index.html"),
        help="Source HTML document (default: index.html beside this script)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_name("fluidballs-webgl-single.html"),
        help="Output HTML document (default: fluidballs-webgl-single.html)",
    )
    args = parser.parse_args()

    source = args.source.resolve()
    output = args.output.resolve()

    try:
        stylesheets, scripts = build(source, output)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))

    print(f"Built: {output}")
    print(f"Inlined {len(stylesheets)} stylesheet(s) and {len(scripts)} script(s).")
    print(f"Size: {output.stat().st_size:,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
